Repository voila-dashboards/voici, pull requests merged in 2023-04, with the labels that each got.

#55 Troubleshoot CI
  yarn.lock
Labels: maintenance

#56 Create `__main__.py`
  voici/__main__.py
Labels: enhancement

#52 Create CONTRIBUTING.md
  .github/workflows/update_playwright_references.yaml
  CONTRIBUTING.md
  environment.yml
Labels: documentation

#50 Update to `jupyterlite-core>=0.1.0,<0.2.0`
  environment.yml
  pyproject.toml
Labels: maintenance

#59 Fix handling of the base url to enable the Service Worker
  demo/notebooks/iris.csv
  demo/notebooks/voici.ipynb
  packages/voici/package.json
  ui-tests/tests/voici.test.ts-snapshots/voici-simple-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-simple-material-linux.png
  voici/exporter.py
  voici/tree_exporter.py
  yarn.lock
Labels: enhancement

#60 Update the documentation
  CONTRIBUTING.md
  docs/Makefile
  docs/changelog.md
  docs/conf.py
  docs/configuration.md
  docs/contributing.md
  docs/deploy.md
  docs/doc-requirements.txt
  docs/environment.yml
  docs/index.md
  docs/install.md
  docs/make.bat
  docs/source/_static/main_stylesheet.css
  docs/source/deploy.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/voila-logo.svg
  package.json
  pyproject.toml
  readthedocs.yml
Labels: documentation

#63 Fetch theme name from the body data attribute
  packages/voici/src/plugins.ts
Labels: bug

#64 Add badges to the README
  README.md
Labels: documentation

#65 Update CLI
  CONTRIBUTING.md
  voici/addon.py
  voici/app.py
  voici/static/index.html
Labels: enhancement

#66 Update readme
  README.md
Labels: documentation

#67 Add missing `react-dom` module to Webpack shared scope
  packages/voici/package.json
  packages/voici/src/index.ts
Labels: enhancement

#68 Remove old logic for installing piplite packages
  packages/voici/src/app.ts
Labels: maintenance

#71 Remove custom styling
  packages/voici/src/index.ts
  packages/voici/src/tree.ts
  packages/voici/style.css
  packages/voici/style/index.css
  packages/voici/webpack.config.js
  ui-tests/tests/voici.test.ts-snapshots/voici-ipycanvas-linux.png
Labels: enhancement

#73 Update WIP comment
  README.md
Labels: documentation

#72 Fix version printing
  voici/app.py
Labels: bug
