Repository voila-dashboards/voici, pull requests merged in 2023-03, with the labels that each got.

#13 Add `publishConfig` to `package.json`
  packages/voici/package.json
Labels: maintenance

#15 Add releaser workflows to the repo
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#16 Playwright bot: Setup the micromamba env properly
  .github/workflows/update_playwright_references.yaml
Labels: bug

#18 Add README
  README.md
Labels: documentation

#12 Turn into a JupyterLite Addon + support any kernel
  .gitignore
  .prettierignore
  README.md
  demo/environment.yml
  demo/jupyter-lite.json
  demo/voici.ipynb
  demo/widgets/bqplot.ipynb
  demo/widgets/ipycanvas.ipynb
  environment.yml
  packages/voici/package.json
  packages/voici/src/app.ts
  packages/voici/src/global.d.ts
  packages/voici/src/index.ts
  packages/voici/src/plugins.ts
  packages/voici/webpack.config.js
  pyproject.toml
  ui-tests/package.json
  ui-tests/tests/voici.test.ts
  ui-tests/tests/voici.test.ts-snapshots/voici-bqplot-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-ipycanvas-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-simple-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-tree-linux.png
  voici/_version.py
  voici/addon.py
  voici/app.py
  voici/exporter.py
  voici/static/index.html
  voici/static/services.js
  voici/tree_exporter.py
  voici/utils.py
  yarn.lock
Labels: enhancement

#21 Debump versions so that the releaser can make 0.1.0
  package.json
  voici/_version.py
Labels: maintenance

#23 More ui-tests
  ui-tests/tests/voici.test.ts
  ui-tests/tests/voici.test.ts-snapshots/voici-dark-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-subtree-linux.png
Labels: maintenance

#25 Fix `voici build --contents notebooks/ --output-dir dist` use case
  .github/workflows/main.yml
  demo/notebooks/voici.ipynb
  demo/notebooks/widgets/bqplot.ipynb
  demo/notebooks/widgets/ipycanvas.ipynb
  ui-tests/package.json
  voici/addon.py
  voici/tree_exporter.py
Labels: bug

#30 Minor edits to the README
  README.md
Labels: documentation

#31 Require latest voila
  environment.yml
  pyproject.toml
  ui-tests/tests/voici.test.ts
  ui-tests/tests/voici.test.ts-snapshots/voici-subtree-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-tree-linux.png
  voici/addon.py
  voici/tree_exporter.py
Labels: enhancement

#32 Update README instructions
  README.md
Labels: documentation

#33 Add Voila config aliases
  voici/app.py
Labels: enhancement

#34 Fix custom template support
  voici/exporter.py
Labels: bug

#35 Test custom template in ui-tests
  .gitignore
  environment.yml
  ui-tests/package.json
  ui-tests/tests/voici.test.ts
  ui-tests/tests/voici.test.ts-snapshots/voici-simple-material-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-subtree-material-linux.png
  ui-tests/tests/voici.test.ts-snapshots/voici-tree-material-linux.png
Labels: maintenance

#38 Expose the widget manager promise from the `VoiciApp`
  packages/voici/src/app.ts
  packages/voici/src/plugins.ts
Labels: maintenance

#37 Depend on `jupyterlite-core`
  demo/jupyter-lite.json
  environment.yml
  packages/voici/package.json
  packages/voici/src/index.ts
  pyproject.toml
  voici/addon.py
  voici/app.py
  yarn.lock
Labels: maintenance

#39 Add `yarn watch` command to voici package
  packages/voici/package.json
  yarn.lock
Labels: maintenance

#41 Update to `jupyterlite-core>=0.1.0b20`
  demo/jupyter-lite.json
  environment.yml
  packages/voici/package.json
  packages/voici/src/index.ts
  pyproject.toml
  yarn.lock
Labels: maintenance

#42 Update dev dependencies, TypeScript 5
  .eslintrc.js
  .github/workflows/check-release.yml
  lint-staged.config.js
  package.json
  packages/voici/package.json
  packages/voici/src/app.ts
  packages/voici/src/index.ts
  packages/voici/src/manager.ts
  packages/voici/src/plugins.ts
  packages/voici/src/tree.ts
  packages/voici/webpack.config.js
  tsconfig.eslint.json
  ui-tests/playwright.config.js
  ui-tests/tests/voici.test.ts
  yarn.lock
Labels: maintenance

#45 Remove the `reset_stable.sh` script
  pyproject.toml
  scripts/reset-stable.sh
Labels: maintenance

#44 Update to Voila 0.5.0a3
  environment.yml
  packages/voici/package.json
  packages/voici/src/app.ts
  packages/voici/src/index.ts
  packages/voici/src/manager.ts
  packages/voici/src/tree.ts
  pyproject.toml
  yarn.lock
Labels: maintenance

#47 Simplify the script for bumping versions
  RELEASE.md
  package.json
  packages/voici/package.json
  pyproject.toml
  scripts/bump-version.py
Labels: maintenance

#49 Use `ruff` instead of `flake8`, run `black`
  .flake8
  .github/workflows/main.yml
  docs/source/conf.py
  environment.yml
  pyproject.toml
  voici/addon.py
  voici/app.py
  voici/tree_exporter.py
Labels: maintenance
