Repository voila-dashboards/voici, pull requests merged in 2023-10, with the labels that each got.

#95 Enable Playwright trace
  ui-tests/playwright.config.js
Labels: maintenance

#96 Bump jupyterlite
  demo/environment.yml
  environment.yml
  package.json
  packages/voici/package.json
  packages/voici/src/app.ts
  packages/voici/src/main.ts
  pyproject.toml
  ui-tests/playwright.config.js
  voici/tree_exporter.py
  yarn.lock
Labels: enhancement, maintenance

#97 Wait for service worker on start up
  CHANGELOG.md
  README.md
  packages/voici/src/main.ts
Labels: documentation, enhancement
