Repository voila-dashboards/voici, pull requests merged in 2024-01, with the labels that each got.

#105 Update publish workflow for trusted publishers
  .github/workflows/publish-release.yml
  packages/voici/package.json
Labels: maintenance

#107 Switch to using jupyterlite-xeus instead of xeus-python
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  docs/environment.yml
  python/voici-core/yarn.lock
  python/voici/pyproject.toml
  tests/notebooks/environment.yml
Labels: enhancement

#108 Use check-release v2 workflow
  .github/workflows/check-release.yml
Labels: maintenance

#109 Symlink readme
  README.md
  python/voici-core/voici_core/tree_exporter.py
Labels: documentation

#110 README: clarify voici and voici-core differences
  python/voici-core/README.md
  python/voici/README.md
Labels: documentation
